[package]
name = "escalier_hm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = "0.2.8"
itertools = "0.10.5"
im = "15.1.0"

[dev-dependencies]
insta = "1.13.0"
