export declare const a: 5;
export declare const b: <A>(x: A) => A;
export declare const bar: number;
export declare const c: () => 5;
export declare const d: 15;
export declare const e: (f: (arg0: number) => number, x: number) => number;
export declare const foo: (a: number, b: number) => number;
export declare const g: (a: 5, b: 10) => 15;
export declare const h: <A>(f: (arg0: A) => number, x: A, y: A) => number;
export declare const x: number;
export declare const y: number;
export declare const z: number;
