[package]
name = "crochet_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.8.0"
crochet_ast = { version = "0.1.0", path = "../crochet_ast" }
unescape = "0.1.0"

[dev-dependencies]
insta = "1.13.0"
pretty_assertions = "1.2.1"
